
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.nameOverride }}-env-secret"
type: Opaque
stringData:
  .env: |
    {{- range $k, $v := .Values.envFile.secret }}
    {{ printf "%s=%q" $k $v | nindent 4 }}
    {{- end }}
