{{- if .Values.envFile.enabled }}

{{- if and .Values.envFile.config (not .Values.envFile.existingSecretName) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.nameOverride }}-env
data:
  .env: |
{{- range $k, $v := .Values.envFile.config }}
    {{ $k }}={{ $v | quote }}
{{- end }}
---
{{- end }}

{{- if and .Values.envFile.secret (not .Values.envFile.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride }}-env-secret
type: Opaque
stringData:
  .env: |
{{- range $k, $v := .Values.envFile.secret }}
    {{ $k }}={{ $v | quote }}
{{- end }}
{{- end }}

{{- end }}